background {
    monitor =
    color = rgb(0, 0, 0)
}

label {
    monitor =
    text = Ly version 1.1.0  F1 shutdown  F2 reboot  F5 decrease brightness  F6 increase brightness
    color = rgb(255, 255, 255)
    font_size = 11
    font_family = Monospace
    position = 10, -10
    halign = left
    valign = top
}

shape {
    monitor =
    size = 300, 150
    color = rgba(0, 0, 0, 0)
    border_size = 1
    border_color = rgb(255, 255, 255)
    rounding = 0
    position = 0, 0
    halign = center
    valign = center
}

label {
    monitor =
    text = <         logged out         >
    color = rgb(255, 255, 255)
    font_size = 11
    font_family = Monospace
    position = 0, 50
    halign = center
    valign = center
}

label {
    monitor =
    text = wayland  < Hyprland >
    color = rgb(255, 255, 255)
    font_size = 11
    font_family = Monospace
    position = -48, 18
    halign = center
    valign = center
}

label {
    monitor =
    text = login  $USER
    color = rgb(255, 255, 255)
    font_size = 11
    font_family = Monospace
    position = -72, -14
    halign = center
    valign = center
}

label {
    monitor =
    text = password
    color = rgb(255, 255, 255)
    font_size = 11
    font_family = Monospace
    position = -60, -46
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 120, 20
    outline_thickness = 0
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = false
    dots_rounding = -1
    fade_on_empty = false
    font_color = rgb(255, 255, 255)
    font_family = Monospace
    inner_color = rgba(0, 0, 0, 0)
    outer_color = rgba(0, 0, 0, 0)

    placeholder_text = <span>_</span>
    hide_input = false

    position = 44, -46
    halign = center
    valign = center
}

